-- global names
col name format a12
col value format a50
select name, value from v$parameter where name = 'db_domain'
/

col name format a12
col value format a6
select name, value from v$parameter where name = 'global_names'
/

select * from global_name;

select db_link from user_db_links;

SELECT DISTINCT PRIVILEGE AS "Database Link Privileges"
FROM ROLE_SYS_PRIVS
WHERE PRIVILEGE IN ('CREATE SESSION','CREATE DATABASE LINK','CREATE PUBLIC DATABASE LINK')
/

COL OWNER FORMAT a10
COL USERNAME FORMAT A8 HEADING "USER"
COL DB_LINK FORMAT A30
COL HOST FORMAT a50 HEADING "SERVICE"
SELECT * FROM DBA_DB_LINKS
/

COL DB_LINK FORMAT A25
COL OWNER_ID FORMAT 99999 HEADING "OWNID"
COL LOGGED_ON FORMAT A5 HEADING "LOGON"
COL HETEROGENEOUS FORMAT A5 HEADING "HETER"
COL PROTOCOL FORMAT A8
COL OPEN_CURSORS FORMAT 999 HEADING "OPN_CUR"
COL IN_TRANSACTION FORMAT A3 HEADING "TXN"
COL UPDATE_SENT FORMAT A6 HEADING "UPDATE"
COL COMMIT_POINT_STRENGTH FORMAT 99999 HEADING "C_P_S"

SELECT * FROM V$DBLINK
/