SELECT 
  OWNER,
  OBJECT_TYPE,
  COUNT(DISTINCT OBJECT_NAME)
FROM DBA_OBJECTS
WHERE OWNER NOT IN (
  'APEX_030200',
  'APPQOSSYS',
  'DBSNMP',
  'EXFSYS',
  'FLOWS_FILES',
  'MDSYS',
  'ORACLE_OCM',
  'ORDDATA',
  'ORDPLUGINS',
  'ORDSYS',
  'OUTLN',
  'SI_INFORMTN_SCHEMA',
  'SYS',
  'SYSMAN',
  'SYSTEM',
  'XDB',
  'WMSYS',
  'GSMADMIN_INTERNAL',
  'CTXSYS',
  'DVF',
  'DVSYS',
  'LBACSYS',
  'AUDSYS',
  'DBSFWUSER',
  'OJVMSYS',
  'OLAPSYS',
  'REMOTE_SCHEDULER_AGENT'
  )
GROUP BY OWNER, OBJECT_TYPE
ORDER BY 1,2
/
