-- count and show owner
-- invalid objects (non default user as owner)
-- 
SELECT
  DISTINCT OWNER,
  COUNT(OBJECT_NAME) AS "Invalid objects: "
FROM DBA_OBJECTS
WHERE OWNER NOT IN
    ('SYS',
    'SYSTEM',
	'SYSDBA',
	'SYSMAN',
	'APEX_PUBLIC_USER',
	'LBACSYS', 
	'OUTLN',
	'DVSYS',
	'MDSYS',
	'DVF',
	'OLAPSYS',
	'ORDDATA',
	'ORDSYS',
	'XDB',
	'CTXSYS',
	'CTX_OUTPUT',
	'WMSYS',
	'GSMADMIN_INTERNAL',
	'APPQOSSYS',
	'DBSNMP',
	'ORDPLUGINS',
	'XS$NULL',
	'OJVMSYS',
	'SYS$UMF',
	'DBSFWUSER',
	'GGSYS',
	'SI_INFORMTN_SCHEMA',
	'GSMCATUSER',
	'MDDATA',
	'SYSBACKUP',
	'REMOTE_SCHEDULER_AGENT',
	'GSMUSER',
	'SYSRAC',
	'AUDSYS',
	'DIP',
	'SYSKM',
	'ORACLE_OCM',
	'SYSDG',
	'SPATIAL_CSW_ADMIN_USR',
	'C##DBAAS_BACKUP',
	'ANONYMOUS',
	'EXFSYS',
	'FLOWS_FILES',
	'TSMSYS',
	'MGMT_VIEW',
	'APEX_030200'
  )
AND STATUS = 'INVALID'
GROUP BY OWNER
ORDER BY 1
/